### ISSUE TITLE
Looks blurry from the retina display

### ISSUE THREAD

**Issue by ZoetZhong** [TheBolliwood/circleChart#2]
I Put it in a web app page , it looks blurry from the iPhone's retina display.

**Comment by TheBolliwood** [comment]
You are right, investigating further soon(tm).

**Comment by TheBolliwood** [comment]
should be fixed with f16f86daf47aca62fe197d07be2ceb7bb31e8213

**Comment by TheBolliwood** [comment]
included in v2.2

**Comment by ZoetZhong** [comment]
Thank you!
